### ISSUE TITLE
Share-dependencies with instance VUE-3

### ISSUE THREAD

**Issue by y-sanchez** [vue-microfrontends/shared-dependencies#2]
Hi, 

I have two importmaps, one to expose the microfrontends and another to libs shared beetween apps: 

root-conf projet: index.ejs ( use : single-page-layout) 

<script type="systemjs-importmap" src="http://localhost:9001/importmaplibs.json"></script>
preview of importmaplibs: 
![image](https://user-images.githubusercontent.com/26004938/98531154-3711be00-2280-11eb-95c0-e2b58ff6827a.png)

<script type="systemjs-importmap" src="http://localhost:9001/importmap.json"></script>

On each microfrontend vue3, i have the conf: 

![image](https://user-images.githubusercontent.com/26004938/98534505-e355a380-2284-11eb-9fe6-dbb92f8736f5.png)

When starting, i have applications which do not appear, so far no error in the broswer 
Is it possible that there was a problem loading the vue3 instance?

Thanks

**Comment by internettrans** [comment]
Hi @y-sanchez - loading Vue 3 has been a bit problematic. It is being discussed in https://github.com/systemjs/systemjs/issues/2272. You should see an error in the console, though, instead of nothing. here's something you can run in the browser console to check:

```js
await System.import('vue')

// make sure the logged object has mount/unmount functions on it
```

The github issue I linked to above shows one way of loading vue 3 via a new systemjs extra. However, I also have plans to create a version of vue 3 that works with systemjs in the esm-bundle repos.

I'm closing this since I think the systemjs issue is the better place to track this. Feel free to comment further or reopen.
